{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hawkfish.fullname" . }}
  labels:
    {{- include "hawkfish.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hawkfish.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.hawkfish.port }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  egress:
  - {}  # Allow all egress by default
  {{- end }}
{{- end }}
