{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hawkfish.fullname" . }}-data
  labels:
    {{- include "hawkfish.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.isos.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hawkfish.fullname" . }}-isos
  labels:
    {{- include "hawkfish.labels" . | nindent 4 }}
    app.kubernetes.io/component: isos
  {{- with .Values.persistence.isos.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.isos.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.isos.size }}
  {{- if .Values.persistence.isos.storageClass }}
  {{- if (eq "-" .Values.persistence.isos.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.isos.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}