apiVersion: v1
kind: Service
metadata:
  name: {{ include "hawkfish.fullname" . }}
  labels:
    {{- include "hawkfish.labels" . | nindent 4 }}
  {{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: "/redfish/v1/metrics"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hawkfish.selectorLabels" . | nindent 4 }}
