name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install -e .[dev]
      
    - name: Lint with ruff
      run: ruff check .
      
    - name: Type check with mypy
      run: mypy src
      
    - name: Run tests
      run: pytest tests/ -v
      
    - name: Test app startup
      run: |
        timeout 10s python -m hawkfish_controller --help || true
        echo "✅ App can start successfully"